apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-4
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'  
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
  - name: read-only
    description: "this role can be used for reading the applications"
    policies:
    - p, proj:project-4:read-only, applications, get, project-4/*, allow
