apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-roles
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
