apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  project: project-1
  source:
    repoURL: https://github.com/nitishfy/argocd-tutorial.git
    targetRevision: main
    path: argocd-application/helm/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default