apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample-application
spec:
  project: default
  source:
    helm:
      releaseName: application-from-nginx
      valueFiles:
        - custom-values.yaml
    repoURL: https://github.com/nitishfy/argocd-tutorial
    targetRevision: main
    path: argocd-application/helm/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default