apiVersion: v1
kind: Secret
metadata:
  name: argocd-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nitishfy/json-parser.git
  username: argocd-private-repo
  password: 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
